#pragma once

namespace waki
{
    enum class Key
    {
        EER           = -1,
        TAB           = 9,   // 'TAB'
        ENTER         = 10,  // '\n'
        ESCAPE        = 27,  // 'ESC'
        SPACE         = 32,  // ' '
        EXCLAMATION   = 33,  // '!'
        DOUBLE_QUOTE  = 34,  // '"'
        HASH          = 35,  // '#'
        DOLLAR        = 36,  // '$'
        PERCENT       = 37,  // '%'
        AMPERSAND     = 38,  // '&'
        SINGLE_QUOTE  = 39,  // '\''
        LEFT_PAREN    = 40,  // '('
        RIGHT_PAREN   = 41,  // ')'
        ASTERISK      = 42,  // '*'
        PLUS          = 43,  // '+'
        COMMA         = 44,  // ','
        MINUS         = 45,  // '-'
        PERIOD        = 46,  // '.'
        SLASH         = 47,  // '/'
        DIGIT_0       = 48,  // '0'
        DIGIT_1       = 49,  // '1'
        DIGIT_2       = 50,  // '2'
        DIGIT_3       = 51,  // '3'
        DIGIT_4       = 52,  // '4'
        DIGIT_5       = 53,  // '5'
        DIGIT_6       = 54,  // '6'
        DIGIT_7       = 55,  // '7'
        DIGIT_8       = 56,  // '8'
        DIGIT_9       = 57,  // '9'
        COLON         = 58,  // ':'
        SEMICOLON     = 59,  // ';'
        LESS_THAN     = 60,  // '<'
        EQUALS        = 61,  // '='
        GREATER_THAN  = 62,  // '>'
        QUESTION      = 63,  // '?'
        AT_SIGN       = 64,  // '@'
        UPPER_A       = 65,  // 'A'
        UPPER_B       = 66,  // 'B'
        UPPER_C       = 67,  // 'C'
        UPPER_D       = 68,  // 'D'
        UPPER_E       = 69,  // 'E'
        UPPER_F       = 70,  // 'F'
        UPPER_G       = 71,  // 'G'
        UPPER_H       = 72,  // 'H'
        UPPER_I       = 73,  // 'I'
        UPPER_J       = 74,  // 'J'
        UPPER_K       = 75,  // 'K'
        UPPER_L       = 76,  // 'L'
        UPPER_M       = 77,  // 'M'
        UPPER_N       = 78,  // 'N'
        UPPER_O       = 79,  // 'O'
        UPPER_P       = 80,  // 'P'
        UPPER_Q       = 81,  // 'Q'
        UPPER_R       = 82,  // 'R'
        UPPER_S       = 83,  // 'S'
        UPPER_T       = 84,  // 'T'
        UPPER_U       = 85,  // 'U'
        UPPER_V       = 86,  // 'V'
        UPPER_W       = 87,  // 'W'
        UPPER_X       = 88,  // 'X'
        UPPER_Y       = 89,  // 'Y'
        UPPER_Z       = 90,  // 'Z'
        LEFT_BRACKET  = 91,  // '['
        BACKSLASH     = 92,  // '\\'
        RIGHT_BRACKET = 93,  // ']'
        CARET         = 94,  // '^'
        UNDERSCORE    = 95,  // '_'
        BACKTICK      = 96,  // '`'
        LOWER_A       = 97,  // 'a'
        LOWER_B       = 98,  // 'b'
        LOWER_C       = 99,  // 'c'
        LOWER_D       = 100, // 'd'
        LOWER_E       = 101, // 'e'
        LOWER_F       = 102, // 'f'
        LOWER_G       = 103, // 'g'
        LOWER_H       = 104, // 'h'
        LOWER_I       = 105, // 'i'
        LOWER_J       = 106, // 'j'
        LOWER_K       = 107, // 'k'
        LOWER_L       = 108, // 'l'
        LOWER_M       = 109, // 'm'
        LOWER_N       = 110, // 'n'
        LOWER_O       = 111, // 'o'
        LOWER_P       = 112, // 'p'
        LOWER_Q       = 113, // 'q'
        LOWER_R       = 114, // 'r'
        LOWER_S       = 115, // 's'
        LOWER_T       = 116, // 't'
        LOWER_U       = 117, // 'u'
        LOWER_V       = 118, // 'v'
        LOWER_W       = 119, // 'w'
        LOWER_X       = 120, // 'x'
        LOWER_Y       = 121, // 'y'
        LOWER_Z       = 122, // 'z'
        LEFT_BRACE    = 123, // '{'
        PIPE          = 124, // '|'
        RIGHT_BRACE   = 125, // '}'
        TILDE         = 126, // '~'
        ARROW_DOWN    = 258,
        ARROW_UP      = 259,
        ARROW_LEFT    = 260,
        ARROW_RIGHT   = 261,
        BACKSPACE     = 263,
        F1            = 265,
        F2            = 266,
        F3            = 267,
        F4            = 268,
        F5            = 269,
        F6            = 270,
        F7            = 271,
        F8            = 272,
        F9            = 273,
        F10           = 274,
        F11           = 275,
        F12           = 276,
        DELETE        = 330,
        INSERT        = 331,
        PAGE_DOWN     = 338,
        PAGE_UP       = 339,
    };
} // namespace waki